### PR TITLE
Disallow 2D box with 3D points

### LINKED ISSUE #468: Can't build after removing "unused" headers
**Describe the bug**
I get a C++ error when building, I think it's caused by #455.
See https://en.cppreference.com/w/cpp/types/offsetof

**Error output**
```
In file included from cpp/environment/MatchEnv.h:10:0,
                 from cpp/environment/MatchEnv.cc:7:
cpp/util/BiMap.h: In member function ‘const char* BiMap<T, U>::right::getPairPtr_B(const U*) const’:
cpp/util/BiMap.h:252:74: error: expected primary-expression before ‘,’ token
             return reinterpret_cast<const char*>(Item_in) - offsetof(Pair, second);
                                                                          ^
cpp/util/BiMap.h:252:76: error: ‘second’ was not declared in this scope
             return reinterpret_cast<const char*>(Item_in) - offsetof(Pair, second);
                                                                            ^
cpp/util/BiMap.h:252:82: error: there are no arguments to ‘offsetof’ that depend on a template parameter, so a declaration of ‘offsetof’ must be available [-fpermissive]
             return reinterpret_cast<const char*>(Item_in) - offsetof(Pair, second);
                                                                                  ^
cpp/util/BiMap.h:252:82: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
cpp/util/BiMap.h: In instantiation of ‘const char* BiMap<T, U>::right::getPairPtr_B(const U*) const [with T = unsigned int; U = unsigned int]’:
cpp/util/BiMap.h:257:47:   required from ‘BiMap<T, U>::Pair* BiMap<T, U>::right::getPairPtr(const U*) const [with T = unsigned int; U = unsigned int; BiMap<T, U>::Pair = std::pair<unsigned int, unsigned int>]’
cpp/util/BiMap.h:262:30:   required from ‘T& BiMap<T, U>::right::getVal(const U*) const [with T = unsigned int; U = unsigned int]’
cpp/util/BiMap.h:284:26:   required from ‘T& BiMap<T, U>::right::operator[](const U&) [with T = unsigned int; U = unsigned int]’
cpp/environment/MatchEnv.cc:127:75:   required from here
cpp/util/BiMap.h:252:69: error: ‘offsetof’ was not declared in this scope
             return reinterpret_cast<const char*>(Item_in) - offsetof(Pair, second);
```

**System configuration (please complete the following information):**
 - OS: Windows Subsystem for Linux running Ubuntu 16.04
 - Version of Python: 3.6.7
 - Version of compiler: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
 - Version of freud: 703f36bfda6c724abbefcddb63784175145c43a3

### PR DESCRIPTION
**Pull request by bdice**
## Description
Disallows points with `z != 0` in NeighborQuery objects built on a 2D box.

## Motivation and Context
This reduces the likelihood of users accidentally misusing freud's 2D capabilities, or accidentally using a 2D box with a system that should be 3D.

Also resolves #468.

## How Has This Been Tested?
A test was added to ensure the error is raised.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds or improves functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] I have read the [**CONTRIBUTING**](https://github.com/glotzerlab/freud/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] I have updated the documentation (if relevant).
- [x] I have added tests that cover my changes (if relevant).
- [x] All new and existing tests passed.
- [x] I have updated the [Changelog](https://github.com/glotzerlab/freud/blob/master/ChangeLog.md).

### CODE REVIEW

File: freud/_locality.pxd [hunk 1]
```diff
@@ -101,31 +101,30 @@ cdef extern from "LinkCell.h" namespace "freud::locality":
...
+                 const vec3[float]*,
+                 unsigned int) except +
         const vec3[unsigned int] computeDimensions(
             const freud._box.Box &,
             float) const
         unsigned int getNumCells() const
         float getCellWidth() const
         unsigned int getCell(const vec3[float] &) const
         IteratorLinkCell itercell(unsigned int) const
-        vector[unsigned int] getCellNeighbors(unsigned int) const
```
Comment (vyasr) [inline freud/_locality.pxd]: Since `m_cell_neighbors` is basically just a convenient cache, I think it would make sense to leave this function const and just make that object `mutable`.

File: tests/test_locality_NeighborQuery.py [hunk 2]
```diff
@@ -504,6 +504,16 @@ def test_duplicate_cell_shells2(self):
...
+    def test_2d_box_3d_points(self):
+        """Test that points with z != 0 fail if the box is 2D."""
+        L = 10  # Box Dimensions
+        r_max = 2.01  # Cutoff radius
+
+        box = freud.box.Box.square(L)  # Initialize Box
+        points = np.array([[0, 0, 0], [0, 1, 1]])
+        with self.assertRaises(ValueError):
+            self.build_query_object(box, points, r_max)
+
```
Comment (vyasr) [inline tests/test_locality_NeighborQuery.py:516]: Can you also add a test to some 2D method (e.g. PMFTXY2D) and make sure it fails too? Ideally it seems like something to test more systematically but until then at least a spot check or two would be good.

**Review by vyasr — CHANGES_REQUESTED** [review]
Couple minor requests, otherwise good!

File: tests/test_pmft.py [hunk 3]
```diff
@@ -625,6 +625,20 @@ def test_query_args_nn(self):
...
+    def test_2d_box_3d_points(self):
+        """Test that points with z != 0 fail if the box is 2D."""
+        L = 10  # Box Dimensions
+
+        box = freud.box.Box.square(L)  # Initialize Box
+        points = np.array([[0, 0, 0], [0, 1, 1]])
+        angles = np.zeros(points.shape[0])
+        max_width = 3
+        nbins = 3
+        pmft = freud.pmft.PMFTXY2D(max_width, max_width, nbins, nbins)
```
Comment (vyasr) [inline tests/test_pmft.py]: You can now just pass `nbins` (or a tuple `(nbins, nbins)`).

**Review by vyasr — APPROVED** [review]
The bug is because of API changes made upstream.
