### ISSUE TITLE
Can't build after removing "unused" headers

### ISSUE THREAD

**Issue by bdice** [glotzerlab/freud#468]
**Describe the bug**
I get a C++ error when building, I think it's caused by #455.
See https://en.cppreference.com/w/cpp/types/offsetof

**Error output**
```
In file included from cpp/environment/MatchEnv.h:10:0,
                 from cpp/environment/MatchEnv.cc:7:
cpp/util/BiMap.h: In member function ‘const char* BiMap<T, U>::right::getPairPtr_B(const U*) const’:
cpp/util/BiMap.h:252:74: error: expected primary-expression before ‘,’ token
             return reinterpret_cast<const char*>(Item_in) - offsetof(Pair, second);
                                                                          ^
cpp/util/BiMap.h:252:76: error: ‘second’ was not declared in this scope
             return reinterpret_cast<const char*>(Item_in) - offsetof(Pair, second);
                                                                            ^
cpp/util/BiMap.h:252:82: error: there are no arguments to ‘offsetof’ that depend on a template parameter, so a declaration of ‘offsetof’ must be available [-fpermissive]
             return reinterpret_cast<const char*>(Item_in) - offsetof(Pair, second);
                                                                                  ^
cpp/util/BiMap.h:252:82: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
cpp/util/BiMap.h: In instantiation of ‘const char* BiMap<T, U>::right::getPairPtr_B(const U*) const [with T = unsigned int; U = unsigned int]’:
cpp/util/BiMap.h:257:47:   required from ‘BiMap<T, U>::Pair* BiMap<T, U>::right::getPairPtr(const U*) const [with T = unsigned int; U = unsigned int; BiMap<T, U>::Pair = std::pair<unsigned int, unsigned int>]’
cpp/util/BiMap.h:262:30:   required from ‘T& BiMap<T, U>::right::getVal(const U*) const [with T = unsigned int; U = unsigned int]’
cpp/util/BiMap.h:284:26:   required from ‘T& BiMap<T, U>::right::operator[](const U&) [with T = unsigned int; U = unsigned int]’
cpp/environment/MatchEnv.cc:127:75:   required from here
cpp/util/BiMap.h:252:69: error: ‘offsetof’ was not declared in this scope
             return reinterpret_cast<const char*>(Item_in) - offsetof(Pair, second);
```

**System configuration (please complete the following information):**
 - OS: Windows Subsystem for Linux running Ubuntu 16.04
 - Version of Python: 3.6.7
 - Version of compiler: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
 - Version of freud: 703f36bfda6c724abbefcddb63784175145c43a3

**Comment by bdice** [comment]
Follow-up problem: `sqrt` seems to return a `double`, which is incompatible with our templated operator overloads for dividing vectors by scalars. This is probably using the wrong `sqrt`, something from `HOOMDMath.h` or similar. I replaced it with `std::sqrt` and it compiles now.
```
cpp/order/Nematic.cc: In constructor ‘freud::order::Nematic::Nematic(vec3<float>)’:
cpp/order/Nematic.cc:17:21: error: no match for ‘operator/’ (operand types are ‘vec3<float>’ and ‘double’)
     : m_n(0), m_u(u / sqrt(dot(u, u)))
                     ^
```

**Comment by bdice** [comment]
I will fix these two issues inline in #462, since they're tiny fixes.

**Comment by vyasr** [comment]
Your first problem seems windows-specific since I can't reproduce it elsewhere. Probably need to `#include <cstddef>`.

For your second problem, freud has fixed this by using `sqrtf` in some places. Using `std::sqrt` is the right approach, though, because it's overloaded to handle the appropriate inputs.

**Comment by vyasr** [comment]
Resolved in #462.
